Add 2023 info to past conference and proceedings pages
scipy-conference/conference.scipy.org pull request #50
Opened 2024-03-06 16:09 UTC by achabotl

Plus fix standardize date formatting on proceedings page.

Fixes #47.

2024-03-06 16:17 UTC, achabotl commented
@matthewfeickert, Would you be willing to take a quick look at this since you seem to have some bandwidth? Thanks.

2024-03-06 19:13 UTC, matthewfeickert approved these changes
LGTM. Thanks @achabotl

2024-03-06 23:10 UTC, tkoyama010 requested changes

2024-03-06 23:10 UTC, tkoyama010 commented on content/pages/proceedings.md
> + *22nd Python in Science Conference - Austin, Texas (July 10—16, 2023)*
```suggestion
 *22nd Python in Science Conference - Austin, Texas (July 10–16, 2023)*
```

2024-03-07 15:48 UTC, achabotl commented
Thanks for the review and reminding me to link the issue.

2024-03-07 15:48 UTC, merged